application-description: project.description
application-version: project.version
spring:
  jackson.deserialization.READ_UNKNOWN_ENUM_VALUES_AS_NULL: false
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings.trace: false
#      settings.web-allow-others: true
  application:
    name: ms-gps-surveys
  datasource:
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
    hikari:
      auto-commit: true
      minimum-idle: 3
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      default_schema: common
      jdbc.lob.non_contextual_creation: true
  messages:
    basename: i18n/messages

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: '/swagger-ui.html'
    operationsSorter: method